name: PokeSync
version: '2.4.1'
author: GT86
main: me.gt86.pokesync.PokeSync
api-version: 1.20
description: Pixelmon Data Sync Plugin
softdepend:
  - HuskSync
commands:
  pokesync:
    aliases:
      - reloadpokesync
    description: The reload command for PokeSync.
    permission: pokesync.admin