name: BukkitPokeSync
version: '1.0'
author: GT86
main: me.gt86.pokesync.BukkitPokeSync
description: Pixelmon Sync Plugin
softdepend: []
api-version: 1.16

libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'com.mysql:mysql-connector-j:${mysql_driver_version}'
  - 'org.mariadb.jdbc:mariadb-java-client:${mariadb_driver_version}'
  - 'org.xerial.snappy:snappy-java:${snappy_version}'
  - 'org.apache.commons:commons-text:${commons_text_version}'

commands:
  pokesync:
    usage: '/<command> <update/info/reload/migrate>'
    description: 'Manage the PokeSync plugin'
  pmuserdata:
    usage: '/<command> <view/list/delete/restore/pin/dump> <username> [version_uuid]'
    description: 'View, manage & restore player pokemon userdata'