name: PokeSync
version: '1.0'
author: GT86
main: me.gt86.pokesync.BukkitPokeSync
description: Pixelmon Sync Plugin
softdepend: []
api-version: 1.16

libraries:
  - 'redis.clients:jedis:4.3.2'
  - 'com.mysql:mysql-connector-j:8.1.0'
  - 'org.mariadb.jdbc:mariadb-java-client:3.1.4'
  - 'org.xerial.snappy:snappy-java:1.1.9.1'
commands:
  pokesync:
    usage: '/<command> <reload>'
    description: 'Manage the PokeSync plugin'
  pmuserdata:
    usage: '/<command> <view/list/delete/restore/pin/dump> <username> [version_uuid]'
    description: 'View, manage & restore player pokemon userdata'